const books = [
  
  // Classics
  {id: 1, name: "A Study in Scarlet", price: 9.99, author: "Arthur Conan Doyle", image: "aStudyInScarlet.png", category: "Classic", description: "A body found in strange circumstances triggers Holmes's deductive reflexes, while the official police lose themselves in misguided wanderings or arrest innocent citizens. A new murder seems to complicate the story, but it clears it up for Holmes."},
  {id: 2, name: "The Adventures of Sherlock Holmes", price: 9.99, author: "Arthur Conan Doyle", image: "theAdventuresOfSherlockHolmes.png", category: "Classic", description: "In The League of Redheads, a man turns to the detective for advice on the disappearance of a strange society of redheads. In The Boscombe Valley Mystery, Holmes investigates the murder of a man whose son is the prime suspect."},
  {id: 3, name: "The Hound of the Beaskervilles", price: 9.99, author: "Arthur Conan Doyle", image: "theHoundOfTheBaskervilles.png", category: "Classic", description: "In this new case, Sherlock Holmes sends Dr. Watson to investigate the death of Sir Charles Baskerville. According to an ancient legend that haunts the family, Sir Charles has been bitten to death by a mysterious dog."},
  {id: 4, name: "The Memoirs of Sherlock Holmes", price: 9.99, author: "Arthur Conan Doyle", image: "theMemoirsOfSherlockHolmes.png", category: "Classic", description: `The stories of these twelve new adventures, compiled under the title of The Memoirs of Sherlock Holmes in 1894 are varied: "Gloria Scott", "The Hunchback" and "The Internal Patient" try to elucidate crimes that occurred in the past; "The Naval Treaty" is an espionage story; "The landowners of Reigate" and "The Greek interpreter" tell us about greed; or "The stockbroker's office worker", which deals with a scam committed for unspeakable reasons.`},
  {id: 5, name: "The Return of Sherlock Holmes", price: 9.99, author: "Arthur Conan Doyle", image: "theReturnOfSherlockHolmes.png", category: "Classic", description: "In 1891 Sherlock Holmes disappeared. A month later, Dr. Watson announces that the researcher has died during a meeting with Professor Moriarty, his staunchest enemy. But is this how things have really gone?"},
  {id: 6, name: "The Picture of Dorian Gray", price: 9.99, author: "Oscar Wilde", image: "thePictureOfDorianGray.png", category: "Classic", description: "Dorian Gray is a very attractive young aristocrat. After spending a lonely adolescence in the country he returns to London, where he has inherited a mansion. Attracted by the nightlife, he plunges into it at the hands of Lord Henry Wottom."},
  {id: 7, name: "Hamlet", price: 9.99, author: "William Shakespeare", image: "hamlet.png", category: "Classic", description: "Hamlet, probably composed between 1599 and 1601, takes place in Denmark and tells how Prince Hamlet carries out his revenge on his uncle Claudius who murdered Hamlet's father, the king, and holds the usurped crown as well as nuptials with Gertrude, the mother of Hamlet."},
  {id: 8, name: "Julius Caesar", price: 9.99, author: "William Shakespeare", image: "juliusCaesar.png", category: "Classic", description: "The tragedy of Julius Caesar is a tragic work written by William Shakespeare, probably in 1599. It recreates the conspiracy against the Roman dictator, his murder and its aftermath, as well as its place of development: ancient Rome. It is one of several Shakespearean works based on historical facts."},
  {id: 9, name: "Romeo and Juliet", price: 9.99, author: "William Shakespeare", image: "romeoAndJuliet.png", category: "Classic", description: "Two Verona Beach teenangers fall in love despite their feuding families (the Capulets and the Montagues), in an update of William Shakespeare's classic tragedy."},

  // Fantasy
  {id: 10, name: "Harry Potter 1", price: 10.99, author: "J.K Rowling", image: "hp1.png", category: "Fantasy", description: "On his eleventh birthday, Harry Potter discovers that he is the son of two well-known wizards, from whom he has inherited magical powers. He must then go to a famous school of magic and wizardry: Howards."},
  {id: 11, name: "Harry Potter 2", price: 10.99, author: "J.K Rowling", image: "hp2.png", category: "Fantasy", description: "With the summer over, Harry can't wait to leave the house of his hateful uncles. He unexpectedly shows up in his bedroom with Dobby, a house-elf, who announces that he will be in great danger if he returns to Hogwarts."},
  {id: 12, name: "Harry Potter 3", price: 10.99, author: "J.K Rowling", image: "hp3.png", category: "Fantasy", description: "Harry's third year at Hogwarts is threatened by Sirius Black's escape from Azkaban Wizarding Prison. He is about a dangerous wizard who was an accomplice of Lord Voldemort and who will try to take revenge on Harry Potter."},
  {id: 13, name: "Harry Potter 4", price: 10.99, author: "J.K Rowling", image: "hp4.png", category: "Fantasy", description: "After the evidence that Voldemort has returned, Harry will be involved in the traditional Triwizard Tournament. With the help of Ron and Herminone, he will prepare to compete in a new fight that he has not chosen."},
  {id: 14, name: "Harry Potter 5", price: 10.99, author: "J.K Rowling", image: "hp5.png", category: "Fantasy", description: "When a new teacher's ignorance leaves Hogwarts unprepared to fight the demon, Harr teaches a small group of students how to defend themselves against the dark arts."},
  {id: 15, name: "Harry Potter 6", price: 10.99, author: "J.K Rowling", image: "hp6.png", category: "Fantasy", description: "Sixth delivery of the saga of the young wizard, in which Harry discovers a powerful book and, while trying to discover its origins, collaborates with Dumbledore in the search for a series of magical objects that will help in the destruction of Lord Voldemort."},
  {id: 16, name: "Harry Potter 7", price: 10.99, author: "J.K Rowling", image: "hp7.png", category: "Fantasy", description: "Harry, Ron and Hermione leave Hogwarts to continue their mission to destroy the Horcruxes, the secret to Voldemort's power and immortality."},
  {id: 17, name: "The Lord of the Rings 1", price: 10.99, author: "J.R.R Tolkien", image: "lotr1.png", category: "Fantasy", description: "In Middle-earth, the Dark Lord Sauron forged the Great Rings of Power and created one with the power to enslave all of Middle-earth. Frodo Baggins is a hobbit whom his uncle Bilbo makes bearer of the powerful One Ring with the mission of destroying it. Accompanied by his friends, Frodo sets out on a journey to Mordor, the only place where the ring can be destroyed. However, Sauron orders the hunt for the group to retrieve the ring and wipe out Middle-earth."},
  {id: 18, name: "The Lord of the Rings 2", price: 10.99, author: "J.R.R Tolkien", image: "lotr2.png", category: "Fantasy", description: "The hobbits Frodo and Sam discover that Gollum is following them. The creature promises to guide them to the gates of Mordor if they then let it go. Aragorn, Legolas the elf and Gimli the dwarf arrive in the kingdom of Rohan and discover that King Theoden is under the spell of Saruman. The traitor wants control of the kingdom to continue his plans in Mordor, awaiting the war in Middle-earth."},
  {id: 19, name: "The Lord of the Rings 3", price: 10.99, author: "J.R.R Tolkien", image: "lotr3.png", category: "Fantasy", description: "The battle for Middle Earth has begun. Saruman's forces have been destroyed and for the first time there seems to be little hope. However, Sauron's power grows and his interest focuses on Gondor, the last stronghold of men, whose heir is Aragorn. Meanwhile, Frodo and Sam, led by Gollum, continue their perilous mission through Mordor to destroy the ring."},

  // Horror
  {id: 20, name: "The Black Cat", price: 11.99, author: "Edgar Allan Poe", image: "theBlackCat.png", category: "Horror", description: "A young married couple leads a peaceful home life in the company of various pets, including a mysterious black cat. Everything changes when the husband begins to get carried away by the drink. Alcohol makes him irascible and in one of his fits of rage he ends the life of the animal."},
  {id: 21, name: "The Cask of Amontillado", price: 11.99, author: "Edgar Allan Poe", image: "theCaskOfAmontillado.png", category: "Horror", description: "The city celebrates carnivals and both go dressed up. She is very nice to him and, under the pretext of seeking her opinion about a certain amontillado wine of which she has just received a barrel, she manages to make Fortunato descend into the cave of his palace, the Montresor catacombs."},
  {id: 22, name: "The Fall of the House of Usher", price: 11.99, author: "Edgar Allan Poe", image: "theFallOfTheHouseOfUsher.png", category: "Horror", description: "Usher lives prisoner of an indefinable disease, which makes everyone fear for his life. The one who ends up dying is his sister. His mortal remains are deposited in a crypt, but terrible events soon take place that lead to a tragic end."},
  {id: 23, name: "The Masque of the Red Death", price: 11.99, author: "Edgar Allan Poe", image: "theMasqueOfTheRedDeath.png", category: "Horror", description: `The story is based on a story of the same name by Edgar Allan Poe. In the Italy of the Middle Ages, a small town begins to suffer the ravages of a strange epidemic that the locals call "the Red Death". Contagious and deadly, the disease begins to claim far too many lives.`},
  {id: 24, name: "The Raven", price: 11.99, author: "Edgar Allan Poe", image: "theRaven.png", category: "Horror", description: "The last days of the life of Edgar Allan Poe. The writer was found on the streets of Baltimore, in a deplorable state, wearing someone else's clothes, and repeated the name of Reynolds, a polar explorer who is the protagonist of his novels."},
  {id: 25, name: "The Tell-Tale Heart", price: 11.99, author: "Edgar Allan Poe", image: "theTellTalleHeart.png", category: "Horror", description: "The film tells the story of a person obsessed with the sick eye of an old man he lives with... until he finally decides to kill him, tear him to pieces and hide him under the floor of the house..."},
  {id: 26, name: "Carrie", price: 11.99, author: "Stephen King", image: "carrie.png", category: "Horror", description: "Carrie White, a shy teenager raised by a religious fanatic, is constantly humiliated by her high school classmates. However, Carrie is not just any girl, the young woman she possesses psychic powers that manifest when she feels dominated by anger. On prom day, the situation becomes unbearable for him."},
  {id: 27, name: "The Shining", price: 11.99, author: "Stephen King", image: "theShining.png", category: "Horror", description: "Jack Torrance is a man who moves his family into an isolated hotel that he must take care of, hoping to get out of his writing block. While Jack is unable to escape the blockade, psychic visions of his son are increasing."},

  // Romantic
  {id: 28, name: "Emma", price: 12.99, author: "Jane Austen", image: "emma.png", category: "Romantic", description: "We learn about the life of young Emma Woodhouse, who lives in Georgian England. Emma takes care of pairing, sometimes more correctly than others, her friends and family."},
  {id: 29, name: "Persuasion", price: 12.99, author: "Jane Austen", image: "persuasion.png", category: "Romantic", description: "Anne Elliot is an eccentric young woman who lives with her family on the brink of bankruptcy. When Frederick Wentworth, the exuberant ex-lover of hers whom she rejected, is suddenly back, she must make a choice."},
  {id: 30, name: "Pride & Prejudice", price: 12.99, author: "Jane Austen", image: "prideAndPrejudice.png", category: "Romantic", description: "The Bennets have five marriageable daughters between the ages of 15 and 23. Getting them settled with a good marriage is the only hope that her mother can harbor, knowing that her daughters will lose their little fortune when her parents die."},
  {id: 31, name: "Sense & Sensibility", price: 12.99, author: "Jane Austen", image: "senseAndSensibility.png", category: "Romantic", description: `The story centers on two sisters, Elinor and Marianne, whose antagonistic personalities exemplify two possible female responses to the prevailing hypocrisy: "common sense" and "sensitivity." However, both one way and the other entail their dangers.`},
  {id: 32, name: "A Walk to Remember", price: 12.99, author: "Nicholas Sparks", image: "aWalkToRemember.png", category: "Romantic", description: "Young Landon is considered the most handsome and popular boy in high school. One day, following a punishment, he meets Jamie, the preacher's daughter. When they meet, they cannot stand each other, because both are the opposite of the other. However, that does not prevent the two young men from falling in love. The relationship between the popular Landon and the conservative Jamie is not well received by the other students. In addition, the young woman hides a secret from Landon."},
  {id: 33, name: "Dreamland", price: 12.99, author: "Nicholas Sparks", image: "dreamland.png", category: "Romantic", description: "A teenage bounty hunter is torn between helping or capturing a seductive runaway bank robber hiding out in his small town during the Great Depression."},
  {id: 34, name: "The Longest Ride", price: 12.99, author: "Nicholas Sparks", image: "theLongestRide.png", category: "Romantic", description: "Former rodeo champion Luke Collins and student Sophia are in love, but their paths and ideals threaten to tear them apart. Luke prepares his return to the rodeos, while Sophia is about to embark in New York in the world of art, her dream job. Faced with the challenges that the future holds for them, they both take inspiration from Ira, a widowed veteran who longs for the great love of his life, with whom he was married for a lifetime despite life's misfortunes."},
  {id: 35, name: "The Notebook", price: 12.99, author: "Nicholas Sparks", image: "theNotebook.png", category: "Romantic", description: "Love story between Allie Hamilton and Noah Calhoun and remembered in a nursing home, decades after it happened. Based on the book by Nicholas Sparks."},

  // Science Fiction
  {id: 36, name: "Dune", price: 13.99, author: "Frank Herbert", image: "dune.png", category: "Science Fiction", description: `Arrakis, also called "Dune", has become the most important planet in the universe. Around him begins a gigantic struggle for power that culminates in an interstellar war.`},
  {id: 37, name: "1984", price: 13.99, author: "George Orwell", image: "ninteenEighty-Four.png", category: "Science Fiction", description: "Based on Orwell's novel, a man tries to keep hope in a totalitarian and repressive society. After falling in love with a young girl, they try to keep their love alive but hidden from the all-knowing Big Brother. This dark and virtual dictator seems to know what each one thinks in the corners of the mind."},
  {id: 38, name: "I, Robot", price: 13.99, author: "Isaac Asimov", image: "iRobot.png", category: "Science Fiction", description: "In the year 2035, robots are part of everyday life. When trust in them is broken, only one man against the whole system sees it coming."},
  {id: 39, name: "Around the World in Eigthy Days", price: 13.99, author: "Jules Verne", image: "aroundTheWorldInEigthyDays.png", category: "Science Fiction", description: "In 1872 a wealthy London gallant, Phileas Fogg, bets his entire fortune that he will go around the world in 80 days. Accompanied by the domestic Passepartout, he leaves London for a formidable race against time. Inspector Fix, convinced that Fogg is the perpetrator of a robbery, follows him everywhere."},
  {id: 40, name: "Journey to the Center of the Earth", price: 13.99, author: "Jules Verne", image: "journeyToTheCenterOfTheEarth.png", category: "Science Fiction", description: "During a scientific expedition in Iceland, the scientist Trevor Anderson, his nephew Sean and Hannah, the guide who accompanies them, get trapped in a cave."},
  {id: 41, name: "The Mysterious Island", price: 13.99, author: "Jules Verne", image: "theMysteriousIsland.png", category: "Science Fiction", description: "Sean receives a distress call from a mysterious island that does not appear on the maps. It is a place with strange forms of life. Sean will undertake the search accompanied by his stepfather, a helicopter pilot and his temperamental daughter, to try to rescue the only inhabitant of it."},
  {id: 42, name: "The Hunger Games 1", price: 13.99, author: "Suzanne Collins", image: "theHungerGames1.png", category: "Science Fiction", description: `To demonstrate its power, the regime of the totalitarian state of Panem organizes every year "The Hunger Games". In them, 24 young people compete against each other in a battle in which there can only be one survivor. Young Katniss volunteers to participate in the games to save her sister. Next to her will participate Peeta, a young man whom she has known since childhood and who is in love with her. However, the Capitol wants to turn them into opponents.`},
  {id: 43, name: "The Hunger Games 2", price: 13.99, author: "Suzanne Collins", image: "theHungerGames2.png", category: "Science Fiction", description: "Katniss Everdeen returned home safely after winning the 74th edition of the Hunger Games with her partner Peeta. However, now the Capitol forces them to abandon their family and friends again to participate in the Victory Tour through all the districts. Meanwhile, President Snow is preparing a new edition of the Games, which will transform Panem forever."},
  {id: 44, name: "The Hunger Games 3", price: 13.99, author: "Suzanne Collins", image: "theHungerGames3.png", category: "Science Fiction", description: "Katniss Everdeen finds herself in District 13 after wrecking the games for good. Under the leadership of Commander Coin and the advice of her most loyal friends, Katniss spreads her wings as she fights to save Peeta Mellark and a nation emboldened by her bravery from him."},
  {id: 45, name: "The Hunger Games 4", price: 13.99, author: "Suzanne Collins", image: "theHungerGames4.png", category: "Science Fiction", description: "Finally District 13 manages to rescue Peeta Mellark from the clutches of the Capitol. The psychological torture has taken its toll on the young man and he is convinced that Katniss is a dangerous mutt that must be ended. Along with a group of friends, Peeta and Katniss embark on a daring mission to liberate Panem. The young heroine will realize that not only her survival is at stake, but also everyone's future."},
];

const storeBooksLS = (books) => {
  localStorage.setItem("books", JSON.stringify(books));
}

const loadBooksLS = () => {
  return JSON.parse(localStorage.getItem("books")) || [];
}

storeBooksLS(books);
